### ISSUE TITLE
PEER REVIEW 1

### ISSUE THREAD

**Issue by IzatheWriter** [guinea-pigg/Pagination_in_API_Documentation#2]
I read your work and loved it :)
It's well-organized. I like the chapters you created. They help the reader to quickly find the right content. 
The text reads well either, nothing boring there. 

I only spotted a few spelling mistakes.

In Pagination styles and patterns chapter:
 
1) The client (i.e. a person who uses an aPI) can divide large a >>> API (capital letters)
2) Tt >>> _IT_ could be _a a_ <<<< (you used two articles here) list of posts, articles, or comments.

**Comment by guinea-pigg** [comment]
Iza, thank you for your review and comment! I've corrected the mistakes you've pointed out :)
