### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by KarolinaGa** [guinea-pigg/Pagination_in_API_Documentation#3]
Cześć Magda, 

dobrze się czyta, zwięźle i na temat :) 
Dwie rzeczy, które zauważyłam: 

- W tym rozdziale na początku zdania pojawia się: "**{: .highlight }** Pagination in API documentation refers to....."
 https://github.com/guinea-pigg/Pagination_in_API_Documentation/blob/f873cd3e527d47649c8bf7aaa1513d91ecf31eb4/chapters/Pagination_in_API_Documentation_Introduction.md?plain=1#L12

- Tutaj chyba API z wielkiej litery?
The client (i.e. a person who uses an **aPI**) can divide large amount of data retrieved from an API by adding certain parameters to their query.
 https://github.com/guinea-pigg/Pagination_in_API_Documentation/blob/f873cd3e527d47649c8bf7aaa1513d91ecf31eb4/chapters/Pagination_Styles_and_Patterns.md?plain=1#L16

**Comment by guinea-pigg** [comment]
Karolina, dziękuję za Twoje review i komentarze! Poprawiłam to, co wskazałaś :)
