### ISSUE TITLE
Odsyłacze z TOC nie działają; może nie trzeba TOC?

### ISSUE THREAD

**Issue by martab0** [guinea-pigg/Pagination_in_API_Documentation#4]
Odsyłacze kliknięte z TOC na stronie https://guinea-pigg.github.io/Pagination_in_API_Documentation/ dają błąd 404, np. odsyłacz "[Pagination in API Documentation. Introduction](https://guinea-pigg.github.io/Pagination_in_API_Documentation/Pagination_in_API_Documentation_Introduction)".
Odsyłacze do tych samych rozdziałów kliknięte z menu po lewej stronie działają bez zarzutu :-)
Zastanawiam się, czy spis treści jest w ogóle potrzebny na tej stronie?

**Comment by guinea-pigg** [comment]
zrobione, dziękuję!

**Comment by guinea-pigg** [comment]
done :)
