### ISSUE TITLE
Odsyłacze do zewnętrznych stron można zrobić pod tytułami

### ISSUE THREAD

**Issue by martab0** [guinea-pigg/Pagination_in_API_Documentation#5]
Odsyłacze do zewnętrznych stron w podrozdziale https://guinea-pigg.github.io/Pagination_in_API_Documentation/chapters/API_Documentation_Overview.html#api-documentation-examples można by zrobić od razu pod tytułami tych stron, np. tak:
[Reddit API Documentation](https://www.reddit.com/dev/api/): Reddit offers APIs for accessing various aspects of the platform including posts, comments, and user data.

**Comment by guinea-pigg** [comment]
zrobione :)
