### ISSUE TITLE
Instrukcje dla dokumentalisty czy projektanta API?

### ISSUE THREAD

**Issue by martab0** [guinea-pigg/Pagination_in_API_Documentation#6]
Nie jest dla mnie jasne, dla kogo przeznaczone są instrukcje w podrozdziale https://guinea-pigg.github.io/Pagination_in_API_Documentation/chapters/Implementing_Pagination_in_API_Documentation.html#api-endpoint-design-for-pagination: dla dokumentalisty opisującego API czy dla projektanta API?

**Comment by guinea-pigg** [comment]
Moim pierwotnym zamysłem było pokazanie takiego "elementarza" kwestii, które są niezbędne dla początkującego dokumentalisty, by stworzyć dokumentację do API. Tutaj rzeczywiście to wyglądało tak, jakby odbiorcą był designer API. Przekształciłam zatem tekst w tym rozdziale w taki sposób, by zaznaczyć, że to, o czym decyduje designer API i zrozumienie tych elementów ma bezpośredni wpływ na to, jak trzeba będzie podejść do tworzenia dokumentacji. Jeśli w Twojej ocenie trzeba będzie dalszych korekt w tym rozdziale, jestem gotowa!

**Comment by martab0** [comment]
Świetnie! Treść rozdziału jest już bdb i wiadomo, kto co robi.
