### ISSUE TITLE
Przykłady, których brakuje?

### ISSUE THREAD

**Issue by martab0** [guinea-pigg/Pagination_in_API_Documentation#7]
Nie rozumiem podrozdziału https://guinea-pigg.github.io/Pagination_in_API_Documentation/chapters/Implementing_Pagination_in_API_Documentation.html#pagination-examples-in-common-programming-languages: czy tu miały być przykłady, których brakuje? Czy ten rozdział ma tylko wymienić języki (wtedy powinien nazywać się inaczej), a przykłady będą gdzieś indziej?

**Comment by guinea-pigg** [comment]
Ten rozdział miał na celu wymienienie języków programowania, o których istnieniu (w kontekście dokumentacji API) powinien pamiętać tech writer. Po edycji tego całego rozdziału, myślę, że ma to już ręce i nogi :)

**Comment by martab0** [comment]
Tak jest - teraz ma ręce i nogi :-)
