### ISSUE TITLE
Sformułowanie tytułów "...in API Documentation"

### ISSUE THREAD

**Issue by martab0** [guinea-pigg/Pagination_in_API_Documentation#8]
Zastanawiam się nad tytułami "Implementing Pagination in API Documentation", "Best Practices in Paginating API Documentation". Dla mnie brzmią tak, jakby to dokumentacja była paginowana. 

Może wystarczy "Implementing Pagination", "Best Practices in Paginating"?

**Comment by guinea-pigg** [comment]
100% racji. Poprawione :)

**Comment by martab0** [comment]
Jeśli czas pozwoli, przezwij pliki w taki sposób, żeby pasowały do poprawionych tytułów.
