### ISSUE TITLE
Rozdział "Documentation Standards and Guidelines"

### ISSUE THREAD

**Issue by martab0** [guinea-pigg/Pagination_in_API_Documentation#9]
Rozdział ma pełne prawo nazywać się "API Documentation Guidelines for Pagination" :-)

Natomiast ten rozdział nie obroni się (pun intended) bez przykładów. Mamy jeszcze miesiąc - znajdź do tego rozdziału dobre przykłady! Mogą być z jednej wybranej dokumentacji lub z różnych, sama zobaczysz, jak Ci wyjdzie bardziej czytelnie.

**Comment by guinea-pigg** [comment]
Myślę, że nowa wersja rozdziału już ma szansę się obronić ;) Dodałam różne przykłady - nie we wszystkich dokumentacjach informacje o paginacji w ogóle występują, a w tych, w których są, różnią się logiką, strukturą, a także dodatkowymi elementami. Z tego względu sporo opierałam się na czytelnej dokumentacji od X oraz Stripe API. Dodatkowo wpadły też inne przykłady.

**Comment by martab0** [comment]
Tak jest! Przykłady z odsyłaczami do źródeł są bardzo dobre. Rozdział się broni :-)
Proponuję małe usprawnienie - odsyłacze do stron zewnętrznych (poza Twoją dokumentację) zrobić tak, żeby otwierały się w nowej karcie przeglądarki. Zrobię jeden przykład i dam pull request. Jeśli zadziała w tym miejscu, to możesz zrobić to samo ze wszystkimi odsyłaczami do stron zewnętrznych - albo tylko w tym rozdziale, albo w całej pracy. (Ale odsyłaczy pomiędzy rozdziałami Twojej pracy nie zmieniaj).
